### PR TITLE
Update to 3.4.0

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
conda-forge: https://github.com/conda-forge/eigen-feedstock
Upstream: https://gitlab.com/libeigen/eigen/-/tree/3.4.0?ref_type=tags

Needed by:
* vowpalwabbit

### CODE REVIEW

**Comment by lorepirri** [comment]
which destination channel? both of the tickets (this one and `vowpalwabbit`) are empty.

**Review by lorepirri — APPROVED** [review]
LGTM, destination channel?

**Comment by JeanChristopheMorinPerso** [comment]
Eigen goes on defaults

**Review by cbouss — APPROVED** [review]
LGTM

Note that ceres-solver and pdal pin to lower versions of eigen. I believe these should be rebuilt. opencv also depends on eigen at runtime, but without constraint.

There is one breaking change in 3.4:
https://eigen.tuxfamily.org/index.php?title=3.4

**Comment by JeanChristopheMorinPerso** [comment]
@cbouss we need to rebuild even if eigen is a header only library?

**Comment by cbouss** [comment]
> @cbouss we need to rebuild even if eigen is a header only library?

haha well in that case no we don't need to.

**Pull request merged**
